###a=p((1 + r/n)**nt))
p = input("What's the principal amount")
principal_amount = int(p)
rate_of_interest = float(input("Please type rate of interest"))
number_times_interest_compounded = int(input("Number of times the interest is compounded per year"))
number_of_years = float(input("Number of years that interest is calculated for"))
amount = principal_amount * ((1 + rate_of_interest / number_times_interest_compounded) ** (number_times_interest_compounded * number_of_years))
#r_divide_number = (rate_of_interest / number_times_interest_compounded)
#print(r_divide_number)
#superscript = (number_times_interest_compounded * number_of_years)
#print(superscript)
#amount = float(principal_amount(1 + r_divide_number) ** superscript)
print("Amount to be paid", amount)
#print(principal_amount * (1 + r_divide_number) ** superscript)
